### ISSUE TITLE
Netbeans internal formatting feature and PHP CS

### ISSUE THREAD

**Issue by arielstt** [vralfy/phpcsmd#42]
Hi everyone,

I've setup my project to automatically format the code on save by using Netbeans internal function (Source -> Format or 'Alt+Shift+F') but it mess up the formatting valid for PHP CS (like opening brace, for example)

Is there any solution to this?

Thanks!

**Comment by vralfy** [comment]
Change your checkstyle :D

There is no solution out of the box .. maybe you could use an other formating plugin to let your sourcecode fit your rules
